name: SurvivalWars
version: 1.0
main: com.SilverMinded.SurvivalWars.SurvivalWars

authors: [J0que_, Testyflesty]

website: https://github.com/SilverMinded/SurvivalWars

commands: 
  quit:
    description: nope
    usage: nope
    
  reset:
    description: Reset the server
    usage: /reset